"""
Django settings for django_tests_backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from accounts.utils import custom_password_reset_confirm_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o!h@8uz_tbtwvk86c7lp_w@=98)77j#2npb4ng%v7ygcmx+u6r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Cambia a False cuando estés listo para producción

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '6c96644982d2.ngrok-free.app',
    '.ngrok-free.app',
    'manelgram112.pythonanywhere.com',
    'testyourselfcambridge.netlify.app',  # Solo el dominio, sin https://
]

# Application definition

INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Terceros
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'corsheaders',
    'crispy_tailwind',
    'drf_yasg',

    # Tus apps
    'tests_api',
    'users',
    'results',
    'groups',
    'accounts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # DEBE estar al principio
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'django_tests_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # IMPORTANTE para allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_tests_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Carpeta de estáticos para desarrollo
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Carpeta donde Django juntará todos los estáticos para producción
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (uploads, images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# CONFIGURACIONES PERSONALIZADAS
# ============================================

# URLs de frontend (usar variable de entorno si está disponible)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# Password reset
DJANGO_REST_AUTH = {
    'PASSWORD_RESET_CONFIRM_URL': 'password-reset-confirm/{uid}/{token}',
}

DJRESTAUTH_RESET_PASSWORD_CONFIRM_URL = custom_password_reset_confirm_url

REST_AUTH_PASSWORD_RESET_FORM_CLASS = "accounts.forms.CustomPasswordResetForm"

REST_AUTH_SERIALIZERS = {
    'PASSWORD_RESET_SERIALIZER': 'dj_rest_auth.serializers.PasswordResetSerializer',
    'USER_DETAILS_SERIALIZER': 'users.CustomUserDetailsSerializer',
    "PASSWORD_RESET_SERIALIZER": "accounts.serializers.MyPasswordResetSerializer"
}

REST_AUTH_FORMS = {
    'PASSWORD_RESET_FORM': 'passwordReset.CustomPasswordResetForm',
}

REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'users.serializers.CustomRegisterSerializer',
}

# ============================================
# CORS CONFIGURATION
# ============================================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8080",
    "http://127.0.0.1:9000",
    "https://c997f89e58cf.ngrok-free.app",
    "https://14080d84bb16.ngrok-free.app",
    "https://manelgram112.pythonanywhere.com",
    "https://testyourselfcambridge.netlify.app",
]

# Permitir credenciales (cookies, auth headers)
CORS_ALLOW_CREDENTIALS = True

# En desarrollo, permitir todos los orígenes (opcional, solo para debug)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# Headers permitidos
CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'x-csrftoken',
    'accept',
    'accept-encoding',
    'origin',
    'user-agent',
    'x-requested-with',
]

# ============================================
# CSRF CONFIGURATION
# ============================================

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://localhost:5173",  # Por si usas HTTPS localmente
    "https://c997f89e58cf.ngrok-free.app",
    "https://14080d84bb16.ngrok-free.app",
    "https://manelgram112.pythonanywhere.com",
    "https://testyourselfcambridge.netlify.app",
]

# Configuración de cookies CSRF
CSRF_COOKIE_SECURE = False  # True solo en producción con HTTPS
CSRF_COOKIE_HTTPONLY = False  # Debe ser False para poder acceder desde JS
CSRF_COOKIE_SAMESITE = 'Lax' if DEBUG else 'None'
CSRF_USE_SESSIONS = False

# ============================================
# SESSION CONFIGURATION
# ============================================

SESSION_COOKIE_SECURE = False  # True solo en producción con HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax' if DEBUG else 'None'

# ============================================
# AUTHENTICATION CONFIGURATION
# ============================================

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# Modelo de usuario personalizado
AUTH_USER_MODEL = 'users.CustomUser'

# Configuración de allauth
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # 'mandatory', 'optional', o 'none'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3

# Después de login/logout
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_ON_GET = True

# ============================================
# REST FRAMEWORK
# ============================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# ============================================
# EMAIL CONFIGURATION
# ============================================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'testyourselfinfo@gmail.com'
EMAIL_HOST_PASSWORD = 'drhj hbod rvmv cjgx'  # Considera usar variables de entorno
DEFAULT_FROM_EMAIL = 'TestYourself / Info <testyourselfinfo@gmail.com>'

# ============================================
# SOCIAL AUTH (Google)
# ============================================

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
        'APP': {
            'client_id': '123',  # Reemplaza con tu client_id real
            'secret': '456',     # Reemplaza con tu secret real
            'key': ''
        }
    }
}

# ============================================
# CRISPY FORMS
# ============================================

CRISPY_ALLOWED_TEMPLATE_PACKS = ["tailwind"]
CRISPY_TEMPLATE_PACK = "tailwind"

# ============================================
# HEADLESS (para allauth)
# ============================================

HEADLESS_ONLY = True

# ============================================
# STRIPE ESTO PARA EL PROYECTO DE CLASE NO LO UTILIZARÉ PROQUE ES PRIVADO
# ============================================

STRIPE_SECRET_KEY = ""
STRIPE_PUBLIC_KEY = ""
STRIPE_WEBHOOK_SECRET = ""

# ============================================
# LOGGING (para debug)
# ============================================

if DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
            },
            'corsheaders': {
                'handlers': ['console'],
                'level': 'DEBUG',
            },
        },
    }