# Generated by Django 5.2.3 on 2025-08-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
