# Generated by Django 5.2.3 on 2025-07-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField()),
                ('model_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('data', models.JSONField()),
            ],
        ),
    ]
