# Generated by Django 5.2.3 on 2025-07-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='data',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='title',
        ),
        migrations.AddField(
            model_name='exercise',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('B2', 'B2'), ('C1', 'C1')], default='C1', max_length=2),
        ),
        migrations.AddField(
            model_name='exercise',
            name='section',
            field=models.CharField(choices=[('reading', 'Reading and Use of English'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking')], default='reading', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='model_name',
            field=models.CharField(default='model1', max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='part',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
