# Generated by Django 5.2.3 on 2025-07-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_api', '0003_testresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
