# Generated by Django 5.2.3 on 2025-07-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_api', '0004_delete_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=models.CharField(default='https://youtu.be/fwBB6Fhj8jQ?si=2IHwIq9i21tCqQfP', max_length=50),
        ),
    ]
