# Generated by Django 5.2.3 on 2025-07-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_api', '0005_exercise_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='explanation',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
