# Generated by Django 5.2.3 on 2025-07-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_api', '0006_exercise_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='eunciado',
            field=models.CharField(default='', max_length=500),
        ),
    ]
