# Generated by Django 5.2.3 on 2025-07-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_api', '0007_exercise_eunciado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='eunciado',
            new_name='enunciado',
        ),
    ]
