# Generated by Django 5.2.3 on 2025-08-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_api', '0008_rename_eunciado_exercise_enunciado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='section',
            field=models.CharField(choices=[('reading', 'Reading'), ('use_of_english', 'Use of English'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking')], default='reading', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.CharField(default='https://youtu.be/fwBB6Fhj8jQ?si=2IHwIq9i21tCqQfP', max_length=255),
        ),
    ]
