# Generated by Django 5.2.3 on 2025-08-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_api', '0009_alter_exercise_section_alter_exercise_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='enunciado',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
