# Generated by Django 5.2.3 on 2025-08-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_api', '0011_alter_exercise_level_alter_exercise_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='part',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
