# Generated by Django 5.2.3 on 2025-08-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_api', '0012_alter_exercise_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('B2', 'B2'), ('C1', 'C1')], default='C1', max_length=2),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='part',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
