# Generated by Django 5.2.3 on 2025-08-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_api', '0013_alter_exercise_level_alter_exercise_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='part',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='section',
            field=models.CharField(choices=[('reading', 'Reading'), ('use_of_english', 'Use of English'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking')], default='reading', max_length=20),
        ),
    ]
