# Generated by Django 5.2.3 on 2025-08-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_api', '0014_alter_exercise_part_alter_exercise_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='enunciado',
            field=models.CharField(blank=True, default='Which person', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('B2', 'B2'), ('C1', 'C1')], default='B2', max_length=2),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='part',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
