# Generated by Django 5.2.3 on 2025-08-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_api', '0015_alter_exercise_enunciado_alter_exercise_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='enunciado',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('B2', 'B2'), ('C1', 'C1')], default='C1', max_length=2),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='part',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
