# Generated by Django 5.2.3 on 2025-08-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_api", "0018_alter_exercise_enunciado_alter_exercise_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="transcription",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="part",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="section",
            field=models.CharField(
                choices=[
                    ("reading", "Reading"),
                    ("use_of_english", "Use of English"),
                    ("listening", "Listening"),
                    ("writing", "Writing"),
                    ("speaking", "Speaking"),
                ],
                default="listening",
                max_length=20,
            ),
        ),
    ]
