# Generated by Django 5.2.3 on 2025-10-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_api", "0019_exercise_transcription_alter_exercise_part_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="level",
            field=models.CharField(
                choices=[("B2", "B2"), ("C1", "C1")], default="C1", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="part",
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="section",
            field=models.CharField(
                choices=[
                    ("reading", "Reading"),
                    ("use_of_english", "Use of English"),
                    ("listening", "Listening"),
                    ("writing", "Writing"),
                    ("speaking", "Speaking"),
                ],
                default="use_of_english",
                max_length=20,
            ),
        ),
    ]
