# Generated by Django 5.2.3 on 2025-10-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_api", "0020_alter_exercise_level_alter_exercise_part_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="exercise_images/"
            ),
        ),
    ]
