# Generated by Django 5.2.3 on 2025-10-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_api", "0021_exercise_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="image",
        ),
        migrations.AddField(
            model_name="exercise",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="exercise_images/"
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="exercise_images/"
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="exercise_images/"
            ),
        ),
    ]
